I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 70, in script
    menu():
  File "game/script.rpy", line 71, in <module>
    "Zoe (Social Media)" if must_meet_zoe:
NameError: name 'must_meet_zoe' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 70, in script
    menu():
  File "C:\Users\Alisa\Downloads\renpy-7.4.10-sdk/renpy/ast.py", line 1688, in execute
    choice = renpy.exports.menu(choices, self.set, args, kwargs, item_arguments)
  File "C:\Users\Alisa\Downloads\renpy-7.4.10-sdk/renpy/exports.py", line 1028, in menu
    condition = renpy.python.py_eval(condition)
  File "C:\Users\Alisa\Downloads\renpy-7.4.10-sdk/renpy/python.py", line 2276, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\Alisa\Downloads\renpy-7.4.10-sdk/renpy/python.py", line 2269, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 71, in <module>
    "Zoe (Social Media)" if must_meet_zoe:
NameError: name 'must_meet_zoe' is not defined

Windows-10-10.0.19041
Ren'Py 7.4.10.2178
3 Nights an Intern @ Team Liquid 1.0
Fri Nov 12 10:52:56 2021
